### ISSUE TITLE
cts (pts?)openshift updates - security, memory

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-charts#130]
The current cts chart fails due to security limitations on openshift
```
  Warning  FailedCreate  77s (x15 over 2m40s)  statefulset-controller  create Pod cts-kafka-0 in StatefulSet cts-kafka failed error: pods "cts-kafka-0" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group, spec.containers[0].securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000670000, 1000679999], provider "ibm-restricted-scc": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "sparkscc": Forbidden: not usable by user or serviceaccount, provider "ibm-anyuid-scc": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "ibm-anyuid-hostpath-scc": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "ibm-anyuid-hostaccess-scc": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "ibm-privileged-scc": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

Approaches to fix include
* Use strimzi, as with our other charts. This also means cts will work on apple silicon & pi - though the startup does take significantly longer (several mintutes). However given CTS can take a long time to run this is likely not an issue
* Try and fix up the default security context etc as setup by the current cts chart
* Add the service account used for this chart in openshift to a less restrictive scc. This involves no code changes, but may impact anyone trying to run these charts

I will propose the first option, as it is aligned with our changes for the base/lab charts. In future it would also allow for better/more realistic kafka throughput with multiple brokers easily scaled.

Some hostnames etc may change
cc: @cmgrote

**Comment by cmgrote** [comment]
I'm fine going to Strimzi assuming that this doesn't increase resource requirements to run the charts. As-is I can just manage to run the CTS chart locally (as we have no project-level cluster against which to test).

If Strimzi increases the number of cores required (or less importantly memory) then I'd probably argue against the first option, as I'll have no way to test the XT connector in a repeatable way.

**Comment by planetf1** [comment]
Currently testing them out, though on a 3x16GB cluster. 
 When I've run locally before 6-8GB has been ok
 Actually I just dropped you a slack message about memory requirements, as the current spec exceeds this (16/32)
 Looks like this is worth checking out & varying
 On strimzi - I don't expect much of a difference - though it might be slightly more.

**Comment by planetf1** [comment]
Initially the egeria-cts chart was failing on a 3x16ram/4core cluster with
```
  Warning  FailedScheduling        20m                default-scheduler  0/3 nodes are available: 1 Insufficient memory, 3 Insufficient cpu.
```

**Comment by planetf1** [comment]
wait-for-platform also fails on openshift with:
```
 "message": "endpoints \"cts-platform\" is forbidden: User \"system:serviceaccount:cts1:cts-cts\" cannot get resource \"endpoints\" in API group \"\" in the namespace \"cts1\"",
```

In the egeria-base & lab charts we have an extra rbac for this - will add

**Comment by planetf1** [comment]
5-10 mins after starting:
```
$ kubectl top pods                                                                                [21:08:39]
NAME                                           CPU(cores)   MEMORY(bytes)
cts-platform-8b8f6bcb9-64b7g                   413m         3115Mi
cts-strimzi-entity-operator-546b5ddc5b-n9w49   10m          506Mi
cts-strimzi-kafka-0                            43m          564Mi
cts-strimzi-zookeeper-0                        16m          224Mi
strimzi-cluster-operator-587cb79468-zwbwb      1m           249Mi
```

**Comment by planetf1** [comment]
@cmgrote I think you have a single 32GB machine running k8s? I imagine if I used a single 32GB node in a future test, running openshift, and it works we should be ok.

What are your cpu concerns? The operator just operated on the cluster config so the overhead is low

**Comment by planetf1** [comment]
I updated the charts for the 3.6 release - there is some followon work here to reduce memory requirements -- I did not notice particular high memory usage in my test, just a request to reserve a lot. Will continue fix in later updates

**Comment by planetf1** [comment]
With the current mem/resource settings, the CTS chart fails in my openshift cluster (3 nodes, 16GB each, 4 CPUs) with:

```
  Warning  FailedScheduling  112s  default-scheduler  0/3 nodes are available: 1 Insufficient memory, 3 Insufficient cpu.
  Warning  FailedScheduling  51s   default-scheduler  0/3 nodes are available: 1 Insufficient memory, 3 Insufficient cpu.

```

Based on the default of

```
    Limits:
      cpu:     4
      memory:  16Gi
    Requests:
      cpu:      2
      memory:   8Gi
```

**Comment by planetf1** [comment]
Seem to be good for now. please reopen if issues seen or raise new issue
