### ISSUE TITLE
Optional resource specification

### ISSUE THREAD

**Issue by zoranid** [odpi/egeria-charts#8]
On some K8s clusters like IBM ICP we must explicitly specify resource for each pod. It is ICP requirement. Also, performance wise some Egeria components work much better with more resources available. On ICP, Atlas pod, for example, wouldn't even start without at least 2 cpus, but significant improvement is visible when cpu = 4, while igcproxy requires 2 cpus. 
It should be possible to optionally specify resources  for each pod in values.yaml E.g. (suggested def values)
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 10m
              memory: .01Gi

**Comment by planetf1** [comment]
The helm chart templates generally try and include a reasonable number of labels to help in identifying egeria related pods, though it's possible they are incomplete - so if you do find missing feel free to raise.

For example one of the egeria platform pods is defined in https://github.com/odpi/egeria-charts/blob/main/charts/odpi-egeria-lab/templates/egeria-dev.yaml . The same pattern is adopted in the egeria-base chart

Here the pods are labelled with:
```
        app.kubernetes.io/name: {{ include "myapp.name" . }} >> this is the name of the chart
        app.kubernetes.io/instance: {{ .Release.Name }} >> this is the helm release
        app.kubernetes.io/component: dev >> We use different labels for each component (ie each platform, the ui etc)
```     
Looking at one of my recent deployments of the lab chart I see these labels in practice:

```
              app.kubernetes.io/component=dev
              app.kubernetes.io/instance=lab
              app.kubernetes.io/name=odpi-egeria-lab
```

This is as expected.

I'll close for now as this has been open for long - apologies for the late reply. 

As above if you want to suggest doc improvements, or alternate labels please do.

The next focus is going to be around the k8s operator, so the point about use of useful labels to aid in deployment-specific requirements is a good one.
